name: Manual Run

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      simulation:
        required: true
        description: 'Simulación que se desea ejecutar'    

  # Allows you to run this workflow manually from the Actions tab
 
jobs:
  # This workflow contains a single job called "build"
  Compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Compilando Java + maven
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      # Runs a set of commands using the runners shell
      - name: Step 3 - Install Maven Dependencies
        run: mvn install -DskipTests

      # Runs a set of commands using the runners shell
      #- name: Step 4 - Download Latest Google Chrome
      #  run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      # Runs a set of commands using the runners shell
      #- name: Step 5 - Install Google Chrome
      #  run: sudo apt install ./google-chrome-stable_current_amd64.deb
      
       # Runs a set of commands using the runners shell
      - name: Step 4 - Build Maven
        run: mvn compil

  Test:
    runs-on: ubuntu-latest
    name: Ejecutando tests
    needs: Compile
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Run Tests
        run: mvn gatling:test '-DclassName=example.simulations.${{ github.event.inputs.automation_label }}'
        
      - name: Step 6 - Generar Reportes (Artifact)
        uses: actions/upload-artifact@v2
        with:
          name: Reporte-EndavaPerformance
          path: target/gatling/
